[project]
name = "philipssignageha"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "sicppy",
]

[tool.uv.workspace]
members = [
    "lib/sicppy",
    "custom_components/philips_sicp_display",
]

[tool.uv.sources]
sicppy = { workspace = true }

[dependency-groups]
dev = [
    "ruff>=0.14.11",
]

[tool.setuptools]
packages = ["sicppy", "philips_sicp_display"]
include-package-data = true

[tool.setuptools.package-dir]
sicppy = "lib/sicppy/sicppy"
philips_sicp_display = "custom_components/philips_sicp_display"

[tool.pyright]
extraPaths = [
    "lib/sicppy",
    "custom_components",
]