[project]
name = "philips-sicp-display"
version = "0.2.3"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "sicppy",
]

[tool.uv.sources]
sicppy = { workspace = true }

[dependency-groups]
dev = [
    "homeassistant>=2026.1.1",
    "voluptuous>=0.15.2",
]

[tool.uv]
default-groups = ["dev"]

[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["philips_sicp_display"]
include-package-data = true

[tool.setuptools.package-dir]
philips_sicp_display = "."

[tool.setuptools.package-data]
philips_sicp_display = [
    "manifest.json",
    "strings.json",
    "translations/**/*.json",
]